# Generated by Django 6.0.6 on 2026-07-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabricantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codigo', models.AutoField(help_text='Código do produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do produto', max_length=70)),
                ('preco_compra', models.FloatField(help_text='Informe o preço de compra')),
                ('preco_venda', models.FloatField(help_text='Informe o preço de venda')),
                ('cor', models.CharField(help_text='Informe a cor do produto', max_length=20)),
                ('imagem', models.CharField(help_text='Informe o nome da imagem', max_length=25)),
                ('fabricantes', models.ForeignKey(help_text='Informe o fabricante', on_delete=django.db.models.deletion.CASCADE, to='fabricantes.fabricantes')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
            },
        ),
    ]
