# Generated by Django 4.2.18 on 2026-07-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='imagem',
        ),
    ]
