# Generated by Django 6.0.6 on 2026-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('codigo', models.AutoField(help_text='Código do fabricante', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do fabricante', max_length=70)),
            ],
            options={
                'verbose_name': 'Fabricantes',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
    ]
