# Generated by Django 6.0.6 on 2026-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cpf', models.CharField(help_text='Informe o CPF do cliente', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do cliente', max_length=70)),
                ('endereco', models.CharField(help_text='Informe o endereço do cliente', max_length=100)),
                ('telefone', models.CharField(help_text='Informe o telefone do cliente', max_length=11)),
                ('uf', models.CharField(help_text='Informe a UF', max_length=2)),
                ('cidade', models.CharField(help_text='Informe a cidade', max_length=50)),
                ('genero', models.CharField(help_text='Informe o gênero', max_length=1)),
                ('contato', models.CharField(help_text='Informe o contato', max_length=100)),
                ('email', models.EmailField(help_text='Informe o e-mail', max_length=100, unique=True)),
                ('senha', models.CharField(help_text='Informe a senha', max_length=256)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
