# Generated by Django 6.0.6 on 2026-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(choices=[('Ronônia', 'Porto Velho'), ('Rio de Janeiro', 'Rio de Janeiro'), ('São Paulo', ' São Paulo'), ('Distrito Federal', 'Brasília'), ('Pernambuco', 'Recife')], help_text='Informe a cidade', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], help_text='Informe o gênero', max_length=1),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='uf',
            field=models.CharField(choices=[('RO', 'RO'), ('RJ', 'RJ'), ('SP', 'SP'), ('DF', 'DF'), ('PE', 'PE')], help_text='Informe a UF', max_length=2),
        ),
    ]
