# Generated by Django 6.0.6 on 2026-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cidade_alter_clientes_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(choices=[('Rondônia', 'Porto Velho'), ('Rio de Janeiro', 'Rio de Janeiro'), ('São Paulo', ' São Paulo'), ('Distrito Federal', 'Brasília'), ('Pernambuco', 'Recife')], help_text='Informe a cidade', max_length=50),
        ),
    ]
